function [errNo] = control_setSensorEnabled(tcp, axis, value)
% brief : Set sensor power supply status, can be switched off to save heat generated by sensor [NUM or RES]
%            Positions retrieved will be invalid when activating this, so closed-loop control should be switched off beforehand
%
% param[in] tcp : TCP/IP connection ID
%           axis:  [0|1|2]
%           value:  true if enabled, false otherwise
% param[out]
%           errNo: errNo


data_send = sprintf('{"jsonrpc": "2.0", "method": "com.attocube.amc.control.setSensorEnabled", "params": [%i, %i], "id": 1, "api": 2}', axis, value);

writeline(tcp, data_send);
data_receive = readline(tcp);
data = jsondecode(data_receive);

errNo = data.result (1);


end


